apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ftnl-web-server-secrets
  annotations:
    dd.dev/fiducia-workload: ftnl-web-server
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-fiducia-kv
  target:
    name: ftnl-web-server-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SUPABASE_URL
      remoteRef:
        key: k8s/file-tunnel/ftnl-web-server/SUPABASE_URL
    - secretKey: SUPABASE_PUBLISHABLE_KEY
      remoteRef:
        key: k8s/file-tunnel/ftnl-web-server/SUPABASE_PUBLISHABLE_KEY
    - secretKey: OTEL_EXPORTER_OTLP_ENDPOINT
      remoteRef:
        key: k8s/file-tunnel/ftnl-web-server/OTEL_EXPORTER_OTLP_ENDPOINT
    - secretKey: OTEL_EXPORTER_OTLP_HEADERS
      remoteRef:
        key: k8s/file-tunnel/ftnl-web-server/OTEL_EXPORTER_OTLP_HEADERS
