apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: file-tunnel
labels:
  - pairs:
      app.kubernetes.io/part-of: file-tunnel
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
images:
  - name: ghcr.io/file-tunnel/ftnl-web-server
    newName: ghcr.io/file-tunnel/ftnl-web-server
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
