apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ftnl-backend-api-secrets
  annotations:
    dd.dev/fiducia-workload: ftnl-backend-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: dd-fiducia-kv
  target:
    name: ftnl-backend-api-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: k8s/file-tunnel/ftnl-backend-api/DATABASE_URL
    - secretKey: SUPABASE_URL
      remoteRef:
        key: k8s/file-tunnel/ftnl-backend-api/SUPABASE_URL
    - secretKey: SUPABASE_SECRET_KEY
      remoteRef:
        key: k8s/file-tunnel/ftnl-backend-api/SUPABASE_SECRET_KEY
    - secretKey: OTEL_EXPORTER_OTLP_ENDPOINT
      remoteRef:
        key: k8s/file-tunnel/ftnl-backend-api/OTEL_EXPORTER_OTLP_ENDPOINT
    - secretKey: OTEL_EXPORTER_OTLP_HEADERS
      remoteRef:
        key: k8s/file-tunnel/ftnl-backend-api/OTEL_EXPORTER_OTLP_HEADERS
