apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ftnl-foundation
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: file-tunnel
  source:
    repoURL: https://github.com/file-tunnel/ftnl-infra.git
    targetRevision: main
    path: kubernetes/foundation
  destination:
    server: https://kubernetes.default.svc
    namespace: file-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
