# Install this file at:
# ORESoftware/k8s-cluster/remote/argocd/apps/file-tunnel.application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/file-tunnel/ftnl-infra.git
    targetRevision: main
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
