apiVersion: v1
kind: ResourceQuota
metadata:
  name: file-tunnel
  namespace: file-tunnel
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "4"
